### ISSUE TITLE
Missing files in block-moc.cpp

### ISSUE THREAD

**Issue by fri-K** [eringerli/QtOpenGuidance#3]
Hi,
I believe you forgot to add some files listened in QtOpenGuidance/src/block/block-moc.cpp, lines 30-34:
#include "moc_GuidanceGlobalPlannerModel.cpp"
#include "moc_GuidanceLocalPlanner.cpp"
#include "moc_GuidancePlannerGui.cpp"
#include "moc_GuidanceStanley.cpp"
#include "moc_GuidanceXte.cpp"

I can't find on master anything that could generate those mocks.

**Comment by eringerli** [comment]
They're made by moc, they are built automaticly on compiling. I recently changed a lot of filenames, please pull the newest commits.
